name: M1MEG_UE1-TP7-essai 
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - matplotlib
  - jupyterlab=3
  - nodejs
  - nbresuse
  - psutil
  - pip
  - ipycytoscape
